### ISSUE TITLE
Release hxcpp-debug-server as separate repository / library

### ISSUE THREAD

**Issue by sh-dave** [vshaxe/hxcpp-debugger#16]
Hi, just wondering why hxcpp-debug-server is a directory in this repo instead of a separate one. I think it would make sense to create a separate one for the library, and link it here via git submodule? This would also make it easier to integrate into projects with build tools that don't rely on haxelib (Kha in my case).

**Comment by Gama11** [comment]
The reason is simply so the lib and the extension can't get out of sync, and we don't have to worry about releasing them separately.

So Kha can't use Haxelibs at all? If so, couldn't you just add the `<User>/.vscode/extensions/vshaxe.hxcpp-debugger-<version>/hxcpp-debug-server` directory as a classpath?

**Comment by sh-dave** [comment]
It can use it, but i don't do it and have all my project dependencies versioned via submodules. But i'll just link this repo instead and manually include the extensions classpath and inject the required macro. (This would have been done automatically by khamake when you `project.addLibrary()` something, as it parses haxelib.json and extraParams.hxml.)

**Comment by Gama11** [comment]
I think having it as a submodule wouldn't have the usually desired effect (reproducibility) anyway. It doesn't _really_ allow you to lock things down to specific versions here, since the hxcpp-debug-server lib depends on the extension (which will at some point auto-update itself out of sync with the submodule, unless you disable auto-updates).
And even if you included the extension iteslf as a submodule too, it technically depends on a specific version of VSCode... ;)

**Comment by sh-dave** [comment]
Oh ok thanks for the info, didn't knew how this all plays together.

I'm still going with the linked submodule for now, as i remembered that khamake should be able to deal with relative paths, so i can just add `project.addLibrary('libs/hxcpp-debugger/hxcpp-debug-server');` without all that manual handling.

Is there any versioning checking going on so that the extension or lib know they don't fit together, and i should update my submodule pointer (or maybe even if the vscode version is unsupported)?

**Comment by Gama11** [comment]
Not really, the current assumption is that things can't be out of sync. ;)

**Comment by sh-dave** [comment]
But won't that fail when the extension updates and the user doesn't install the latest library now as well :thinking:

**Comment by Gama11** [comment]
The extension [automatically updates it when needed](https://github.com/vshaxe/hxcpp-debugger/blob/master/src/Extension.hx).
